checkpoint_dir: '$ROOT_DIR/results/checkpoints/'
log_dir: '$ROOT_DIR/results/logs/'
output_save_path: '$ROOT_DIR/results/results/'
dataset_dir: '$ROOT_DIR/data/cifar10/'
train_epoch: 20
linear_epoch: 50
patience: 5
batch_size: 128
learning_rate: 1e-3
learning_rate_linear: 1e-4
weight_decay: 1e-6
num_workers: 16
dataset: 'cifar10'
random_seed: 1
